// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/proto/assistant.proto

package assistantpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConversationOrchestrator_Converse_FullMethodName   = "/assistant.ConversationOrchestrator/Converse"
	ConversationOrchestrator_GetHistory_FullMethodName = "/assistant.ConversationOrchestrator/GetHistory"
)

// ConversationOrchestratorClient is the client API for ConversationOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationOrchestratorClient interface {
	// Основной диалоговый поток
	Converse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
	// Получение истории диалога
	GetHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
}

type conversationOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationOrchestratorClient(cc grpc.ClientConnInterface) ConversationOrchestratorClient {
	return &conversationOrchestratorClient{cc}
}

func (c *conversationOrchestratorClient) Converse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConversationOrchestrator_ServiceDesc.Streams[0], ConversationOrchestrator_Converse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConversationOrchestrator_ConverseClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

func (c *conversationOrchestratorClient) GetHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, ConversationOrchestrator_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationOrchestratorServer is the server API for ConversationOrchestrator service.
// All implementations must embed UnimplementedConversationOrchestratorServer
// for forward compatibility.
type ConversationOrchestratorServer interface {
	// Основной диалоговый поток
	Converse(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	// Получение истории диалога
	GetHistory(context.Context, *HistoryRequest) (*HistoryResponse, error)
	mustEmbedUnimplementedConversationOrchestratorServer()
}

// UnimplementedConversationOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConversationOrchestratorServer struct{}

func (UnimplementedConversationOrchestratorServer) Converse(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Converse not implemented")
}
func (UnimplementedConversationOrchestratorServer) GetHistory(context.Context, *HistoryRequest) (*HistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedConversationOrchestratorServer) mustEmbedUnimplementedConversationOrchestratorServer() {
}
func (UnimplementedConversationOrchestratorServer) testEmbeddedByValue() {}

// UnsafeConversationOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationOrchestratorServer will
// result in compilation errors.
type UnsafeConversationOrchestratorServer interface {
	mustEmbedUnimplementedConversationOrchestratorServer()
}

func RegisterConversationOrchestratorServer(s grpc.ServiceRegistrar, srv ConversationOrchestratorServer) {
	// If the following call pancis, it indicates UnimplementedConversationOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConversationOrchestrator_ServiceDesc, srv)
}

func _ConversationOrchestrator_Converse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConversationOrchestratorServer).Converse(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConversationOrchestrator_ConverseServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

func _ConversationOrchestrator_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationOrchestratorServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationOrchestrator_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationOrchestratorServer).GetHistory(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConversationOrchestrator_ServiceDesc is the grpc.ServiceDesc for ConversationOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assistant.ConversationOrchestrator",
	HandlerType: (*ConversationOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHistory",
			Handler:    _ConversationOrchestrator_GetHistory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Converse",
			Handler:       _ConversationOrchestrator_Converse_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/assistant.proto",
}

const (
	IntentClassifier_Classify_FullMethodName = "/assistant.IntentClassifier/Classify"
)

// IntentClassifierClient is the client API for IntentClassifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntentClassifierClient interface {
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
}

type intentClassifierClient struct {
	cc grpc.ClientConnInterface
}

func NewIntentClassifierClient(cc grpc.ClientConnInterface) IntentClassifierClient {
	return &intentClassifierClient{cc}
}

func (c *intentClassifierClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, IntentClassifier_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntentClassifierServer is the server API for IntentClassifier service.
// All implementations must embed UnimplementedIntentClassifierServer
// for forward compatibility.
type IntentClassifierServer interface {
	Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	mustEmbedUnimplementedIntentClassifierServer()
}

// UnimplementedIntentClassifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntentClassifierServer struct{}

func (UnimplementedIntentClassifierServer) Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedIntentClassifierServer) mustEmbedUnimplementedIntentClassifierServer() {}
func (UnimplementedIntentClassifierServer) testEmbeddedByValue()                          {}

// UnsafeIntentClassifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntentClassifierServer will
// result in compilation errors.
type UnsafeIntentClassifierServer interface {
	mustEmbedUnimplementedIntentClassifierServer()
}

func RegisterIntentClassifierServer(s grpc.ServiceRegistrar, srv IntentClassifierServer) {
	// If the following call pancis, it indicates UnimplementedIntentClassifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntentClassifier_ServiceDesc, srv)
}

func _IntentClassifier_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentClassifierServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentClassifier_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentClassifierServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntentClassifier_ServiceDesc is the grpc.ServiceDesc for IntentClassifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntentClassifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assistant.IntentClassifier",
	HandlerType: (*IntentClassifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _IntentClassifier_Classify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/assistant.proto",
}

const (
	EntityExtractor_Extract_FullMethodName = "/assistant.EntityExtractor/Extract"
)

// EntityExtractorClient is the client API for EntityExtractor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntityExtractorClient interface {
	Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type entityExtractorClient struct {
	cc grpc.ClientConnInterface
}

func NewEntityExtractorClient(cc grpc.ClientConnInterface) EntityExtractorClient {
	return &entityExtractorClient{cc}
}

func (c *entityExtractorClient) Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, EntityExtractor_Extract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntityExtractorServer is the server API for EntityExtractor service.
// All implementations must embed UnimplementedEntityExtractorServer
// for forward compatibility.
type EntityExtractorServer interface {
	Extract(context.Context, *ExtractRequest) (*ExtractResponse, error)
	mustEmbedUnimplementedEntityExtractorServer()
}

// UnimplementedEntityExtractorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntityExtractorServer struct{}

func (UnimplementedEntityExtractorServer) Extract(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Extract not implemented")
}
func (UnimplementedEntityExtractorServer) mustEmbedUnimplementedEntityExtractorServer() {}
func (UnimplementedEntityExtractorServer) testEmbeddedByValue()                         {}

// UnsafeEntityExtractorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntityExtractorServer will
// result in compilation errors.
type UnsafeEntityExtractorServer interface {
	mustEmbedUnimplementedEntityExtractorServer()
}

func RegisterEntityExtractorServer(s grpc.ServiceRegistrar, srv EntityExtractorServer) {
	// If the following call pancis, it indicates UnimplementedEntityExtractorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntityExtractor_ServiceDesc, srv)
}

func _EntityExtractor_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityExtractorServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityExtractor_Extract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityExtractorServer).Extract(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntityExtractor_ServiceDesc is the grpc.ServiceDesc for EntityExtractor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntityExtractor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assistant.EntityExtractor",
	HandlerType: (*EntityExtractorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Extract",
			Handler:    _EntityExtractor_Extract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/assistant.proto",
}

const (
	WeatherService_GetWeather_FullMethodName = "/assistant.WeatherService/GetWeather"
)

// WeatherServiceClient is the client API for WeatherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherServiceClient interface {
	GetWeather(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherResponse, error)
}

type weatherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherServiceClient(cc grpc.ClientConnInterface) WeatherServiceClient {
	return &weatherServiceClient{cc}
}

func (c *weatherServiceClient) GetWeather(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeatherResponse)
	err := c.cc.Invoke(ctx, WeatherService_GetWeather_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherServiceServer is the server API for WeatherService service.
// All implementations must embed UnimplementedWeatherServiceServer
// for forward compatibility.
type WeatherServiceServer interface {
	GetWeather(context.Context, *WeatherRequest) (*WeatherResponse, error)
	mustEmbedUnimplementedWeatherServiceServer()
}

// UnimplementedWeatherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeatherServiceServer struct{}

func (UnimplementedWeatherServiceServer) GetWeather(context.Context, *WeatherRequest) (*WeatherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeather not implemented")
}
func (UnimplementedWeatherServiceServer) mustEmbedUnimplementedWeatherServiceServer() {}
func (UnimplementedWeatherServiceServer) testEmbeddedByValue()                        {}

// UnsafeWeatherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherServiceServer will
// result in compilation errors.
type UnsafeWeatherServiceServer interface {
	mustEmbedUnimplementedWeatherServiceServer()
}

func RegisterWeatherServiceServer(s grpc.ServiceRegistrar, srv WeatherServiceServer) {
	// If the following call pancis, it indicates UnimplementedWeatherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeatherService_ServiceDesc, srv)
}

func _WeatherService_GetWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).GetWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherService_GetWeather_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).GetWeather(ctx, req.(*WeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherService_ServiceDesc is the grpc.ServiceDesc for WeatherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assistant.WeatherService",
	HandlerType: (*WeatherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeather",
			Handler:    _WeatherService_GetWeather_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/assistant.proto",
}
